Repository external-secrets/external-secrets, pull requests merged in 2025-10, with the labels that each got.

#5391 fix: remove unused secret
  .github/actions/e2e-managed/action.yml
  .github/workflows/e2e-managed.yml
Labels: kind/bug, size/xs, component/github-actions

#5392 fix: issue-5388: Fixes GCP Workload Identity Federation auth issue
  pkg/provider/gcp/secretmanager/workload_identity_federation.go
Labels: kind/bug, size/xs

#5400 feat: make cert auth mount path configurable
  apis/externalsecrets/v1/secretstore_vault_types.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  config/crds/bases/generators.external-secrets.io_clustergenerators.yaml
  config/crds/bases/generators.external-secrets.io_vaultdynamicsecrets.yaml
  deploy/crds/bundle.yaml
  docs/api/spec.md
  pkg/provider/vault/auth_cert.go
Labels: kind/feature, kind/documentation, size/s, size/xs

#5403 chore: release helm chart for v0.20.2
  deploy/charts/external-secrets/Chart.yaml
  deploy/charts/external-secrets/README.md
  deploy/charts/external-secrets/tests/__snapshot__/cert_controller_test.yaml.snap
  deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap
  deploy/charts/external-secrets/tests/__snapshot__/webhook_test.yaml.snap
  tests/__snapshot__/clustergenerator-v1alpha1.yaml
  tests/__snapshot__/clustersecretstore-v1.yaml
  tests/__snapshot__/secretstore-v1.yaml
  tests/__snapshot__/vaultdynamicsecret-v1alpha1.yaml
Labels: kind/chore, size/s

#5406 fix(ci): Remove PAUL
  .github/PAUL.yaml
Labels: kind/bug, area/ci, size/s, component/github-actions

#5414 docs: extend bitwarden example and integration to accomodate the ssh key feature
  docs/examples/bitwarden.md
  docs/snippets/bitwarden-secret-store.yaml
  docs/snippets/bitwarden-secret.yaml
Labels: kind/documentation, size/s
