Repository external-secrets/external-secrets, pull requests merged in 2025-09, with the labels that each got.

#5245 fix: keepersecurity support for shortcuts
  pkg/provider/keepersecurity/client.go
  pkg/provider/keepersecurity/client_test.go
  pkg/provider/keepersecurity/provider.go
Labels: kind/bug, size/xs

#5022 feat: support fetching secrets and certificates by name in Yandex Lockbox & Certificate Manager
  apis/externalsecrets/v1/secretstore_yandex_types.go
  apis/externalsecrets/v1/secretstore_yandexcertificatemanager_types.go
  apis/externalsecrets/v1/secretstore_yandexlockbox_types.go
  apis/externalsecrets/v1/zz_generated.deepcopy.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
  deploy/crds/bundle.yaml
  docs/api/spec.md
  docs/provider/yandex-certificate-manager.md
  docs/provider/yandex-lockbox.md
  pkg/provider/yandex/certificatemanager/certificatemanager.go
  pkg/provider/yandex/certificatemanager/certificatemanager_test.go
  pkg/provider/yandex/certificatemanager/certificatemanagersecretgetter.go
  pkg/provider/yandex/certificatemanager/client/client.go
  pkg/provider/yandex/certificatemanager/client/fakeclient.go
  pkg/provider/yandex/certificatemanager/client/grpcclient.go
  pkg/provider/yandex/common/provider.go
  pkg/provider/yandex/common/secretgetter.go
  pkg/provider/yandex/common/secretsclient.go
  pkg/provider/yandex/lockbox/client/client.go
  pkg/provider/yandex/lockbox/client/fakeclient.go
  pkg/provider/yandex/lockbox/client/grpcclient.go
  pkg/provider/yandex/lockbox/lockbox.go
  pkg/provider/yandex/lockbox/lockbox_test.go
  pkg/provider/yandex/lockbox/lockboxsecretgetter.go
  tests/__snapshot__/clustersecretstore-v1.yaml
  tests/__snapshot__/secretstore-v1.yaml
Labels: kind/feature, kind/documentation, size/l

#5250 chore(charts): Adds new make target for installing unittest plugin
  .github/workflows/helm.yml
  Makefile
  docs/contributing/devguide.md
Labels: kind/documentation, area/charts, kind/chore, size/s, component/github-actions

#5243 feat(release): add new workflow to label first time contributor issues
  .github/workflows/issue-label.yml
Labels: kind/feature, area/release, size/s, component/github-actions

#5154 fix: handle namespace deletion race conditions with finalizers
  deploy/charts/external-secrets/README.md
  deploy/charts/external-secrets/templates/rbac.yaml
  deploy/charts/external-secrets/values.yaml
  pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
  pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
  pkg/controllers/externalsecret/externalsecret_controller.go
Labels: kind/bug, size/m

#5263 fix(akeyless): Upgrade Akeyless Provider Go SDK to v4
  .gitignore
  e2e/go.mod
  e2e/go.sum
  e2e/suites/provider/cases/akeyless/provider.go
  go.mod
  go.sum
  pkg/provider/akeyless/akeyless.go
  pkg/provider/akeyless/akeyless_api.go
  pkg/provider/akeyless/akeyless_test.go
  pkg/provider/akeyless/fake/fake.go
Labels: kind/bug, area/akeyless, kind/dependency, size/s

#5258 feat: add domain field to secretserver provider
  apis/externalsecrets/v1/secretsstore_secretserver_types.go
  cmd/controller/root.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  deploy/crds/bundle.yaml
  docs/api/spec.md
  pkg/provider/secretserver/client_test.go
  pkg/provider/secretserver/provider.go
  pkg/provider/secretserver/provider_test.go
Labels: kind/feature, kind/documentation, size/s

#5265 chore: just updating the crd conformance tests
  tests/__snapshot__/clusterexternalsecret-v1.yaml
  tests/__snapshot__/externalsecret-v1.yaml
  tests/__snapshot__/pushsecret-v1alpha1.yaml
Labels: kind/chore, size/xs

#5162 chore: azure sdk update
  apis/externalsecrets/v1/secretstore_azurekv_types.go
  apis/externalsecrets/v1/zz_generated.deepcopy.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  config/crds/bases/generators.external-secrets.io_acraccesstokens.yaml
  config/crds/bases/generators.external-secrets.io_clustergenerators.yaml
  deploy/crds/bundle.yaml
  docs/api/spec.md
  docs/provider/azure-key-vault.md
  e2e/go.mod
  e2e/go.sum
  e2e/suites/provider/cases/azure/azure_cert.go
  e2e/suites/provider/cases/azure/azure_key.go
  e2e/suites/provider/cases/azure/azure_secret.go
  e2e/suites/provider/cases/azure/provider.go
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/generator/acr/acr.go
  pkg/provider/azure/keyvault/keyvault.go
  pkg/provider/azure/keyvault/keyvault_dual_sdk_test.go
  pkg/provider/azure/keyvault/keyvault_new_sdk.go
Labels: kind/documentation, kind/dependency, kind/chore, size/l

#5270 feat: add support for fetching Secret by Path on Delinea Secret Server provider
  docs/provider/secretserver.md
  e2e/go.mod
  e2e/go.sum
  e2e/suites/provider/cases/secretserver/provider.go
  go.mod
  go.sum
  pkg/provider/secretserver/client.go
  pkg/provider/secretserver/client_test.go
  pkg/provider/secretserver/provider.go
  pkg/provider/secretserver/provider_test.go
  pkg/provider/secretserver/secret_api.go
Labels: kind/feature, kind/documentation, kind/dependency, size/m

#5286 feat: migrate from tibdex to actions/create-github-app-token
  .github/workflows/e2e.yml
  .github/workflows/ok-to-test-managed.yml
  .github/workflows/ok-to-test.yml
  .github/workflows/update-deps.yml
Labels: kind/feature, size/s, component/github-actions

#5307 docs: add burnout prevention strategies and mitigation policy document
  docs/contributing/burnout-mitigation.md
  hack/api-docs/mkdocs.yml
Labels: kind/documentation, size/m

#5313 feat: add missing go sbom
  .github/actions/sign/action.yml
Labels: kind/feature, size/xs, component/github-actions

#5330 test: add more information to potentially flaky test
  pkg/controllers/secretstore/common_test.go
Labels: kind/testing, size/s

#5335 chore(testing): Add licence.check make target
  Makefile
Labels: area/testing, kind/chore, size/xs

#5300 docs(gitlab-variables): document environment scope fallback
  docs/provider/gitlab-variables.md
Labels: kind/documentation, size/s, area/gitlab-variables

#3895 feat: add support for decryption scheme from properties in senhasegura Devops Secrets Management (DSM) provider
  docs/guides/templating.md
  docs/snippets/rsadecrypt-template-v2-external-secret.yaml
  pkg/template/v2/decrypt.go
  pkg/template/v2/decrypt_test.go
  pkg/template/v2/kubernetes.go
  pkg/template/v2/template.go
  pkg/template/v2/template_test.go
Labels: kind/feature, kind/documentation, size/l, size/s, size/m, size/xs, size/xl

#5365 feat(ci): use separate github app for lgtm workflow.
  .github/workflows/lgtm.yml
Labels: kind/feature, area/ci, size/xs, component/github-actions

#5366 fix(ci): run lgtm label remover in pull_request_target context instead
  .github/workflows/lgtm-remove-on-update.yml
Labels: kind/bug, area/ci, size/xs, component/github-actions

#5369 fix: liveness probe would include invalid value `enable`
  deploy/charts/external-secrets/README.md
  deploy/charts/external-secrets/templates/deployment.yaml
  deploy/charts/external-secrets/tests/controller_test.yaml
  deploy/charts/external-secrets/values.schema.json
  deploy/charts/external-secrets/values.yaml
Labels: kind/bug, size/m

#5364 docs: update community meeting section
  README.md
Labels: kind/documentation, size/xs

#5131 feat(gcp): get latest enabled secret
  apis/externalsecrets/v1/secretstore_gcpsm_types.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  deploy/crds/bundle.yaml
  docs/api/spec.md
  docs/provider/google-secrets-manager.md
  docs/snippets/full-secret-store.yaml
  pkg/provider/gcp/secretmanager/client.go
  pkg/provider/gcp/secretmanager/client_test.go
  pkg/provider/gcp/secretmanager/fake/fake.go
Labels: kind/feature, kind/documentation, area/gcp, size/s, size/m

#5368 feat(ci): zizmor github actions vuln scanner
  .github/workflows/zizmor.yml
Labels: kind/feature, area/ci, size/s, component/github-actions

#5374 chore(docs): update pull request approval process
  docs/contributing/process.md
Labels: kind/documentation, kind/chore, size/xs, area/docs

#5377 fix(charts): exclude 'address' key from livenessProbe definition
  deploy/charts/external-secrets/templates/deployment.yaml
Labels: kind/bug, area/charts, size/xs

#5160 feat: add ngrok provider
  CODEOWNERS.md
  apis/externalsecrets/v1/secretstore_ngrok_types.go
  apis/externalsecrets/v1/secretstore_types.go
  apis/externalsecrets/v1/zz_generated.deepcopy.go
  config/crds/bases/external-secrets.io_clustersecretstores.yaml
  config/crds/bases/external-secrets.io_secretstores.yaml
  deploy/crds/bundle.yaml
  docs/api/spec.md
  docs/introduction/stability-support.md
  docs/provider/ngrok.md
  docs/snippets/ngrok-push-secret-with-metadata.yaml
  docs/snippets/ngrok-push-secret.yaml
  docs/snippets/ngrok-secret-store.yaml
  go.mod
  go.sum
  hack/api-docs/mkdocs.yml
  pkg/provider/github/client.go
  pkg/provider/ngrok/client.go
  pkg/provider/ngrok/client_test.go
  pkg/provider/ngrok/fake/fake.go
  pkg/provider/ngrok/provider.go
  pkg/provider/ngrok/provider_test.go
  pkg/provider/register/register.go
  tests/__snapshot__/clusterexternalsecret-v1.yaml
  tests/__snapshot__/clustersecretstore-v1.yaml
  tests/__snapshot__/externalsecret-v1.yaml
  tests/__snapshot__/secretstore-v1.yaml
Labels: kind/feature, kind/documentation, kind/dependency, size/l
