Repository external-secrets/external-secrets, pull requests merged in 2025-08, with the labels that each got.

#5200 chore: add pull request maintenance auto labelling and sizes
  .github/config/labeler.yml
  .github/pull_request_template.md
  .github/workflows/pull-request-label.yml
Labels: kind/feature

#5225 fix: tilt build was failing to rebuild
  Tiltfile
Labels: kind/bug, size/s

#5226 feat: add selectable fields to the CRDs
  .github/workflows/e2e.yml
  apis/externalsecrets/v1/externalsecret_types.go
  config/crds/bases/external-secrets.io_externalsecrets.yaml
  deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
  deploy/crds/bundle.yaml
  docs/api/selectable-fields.md
  e2e/Makefile
  hack/api-docs/mkdocs.yml
Labels: kind/feature, kind/documentation, size/s, component/github-actions

#5224 feat: add setting remote namespace to metadata for kubernetes provider
  docs/provider/kubernetes.md
  pkg/provider/kubernetes/client.go
  pkg/provider/kubernetes/client_test.go
  pkg/provider/kubernetes/metadata.go
Labels: kind/feature, kind/documentation, size/s

#4875 feat: add support for certs only in pkcs12
  docs/guides/templating.md
  pkg/template/v2/pkcs12.go
  pkg/template/v2/pkcs12_test.go
  pkg/template/v2/template.go
Labels: kind/feature, kind/documentation, size/s
